/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_limegroup_gnutella_util_SystemUtils */

#ifndef _Included_com_limegroup_gnutella_util_SystemUtils
#define _Included_com_limegroup_gnutella_util_SystemUtils
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: isLoaded */
/*
 * Class:     com_limegroup_gnutella_util_SystemUtils
 * Method:    idleTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_limegroup_gnutella_util_SystemUtils_idleTime
  (JNIEnv *, jclass);

/*
 * Class:     com_limegroup_gnutella_util_SystemUtils
 * Method:    setFileWriteable
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_limegroup_gnutella_util_SystemUtils_setFileWriteable
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_limegroup_gnutella_util_SystemUtils
 * Method:    setOpenFileLimit0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_limegroup_gnutella_util_SystemUtils_setOpenFileLimit0
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
